### ISSUE TITLE
Bindings to move windows are moving them across screens instead of moving them between adjacent tiles

### ISSUE THREAD

**Issue by bllooi** [domferr/tilingshell#98] opened 2024-07-22 01:48 UTC
**Describe the bug**
The keybindings which control the active windows position in the active layout (ie. Super + Right) is moving windows across displays. It completely skips tiles in the current layout and just moves the window to the other screen

**To Reproduce**
1. Enable the "Keybindings" section in the settings
2. Try to move a window within the layout
3. Skips all tiles and immediately goes to other screen instead of moving between 

**Information (please complete the following):**
 - Tiling Shell version: v12.0
 - GNOME version: 46

**Comment by domferr** [comment] 2024-07-22 07:33
Hey thank you for sharing this bug! Which monitor setup do you have? (For example, I tested in a setup having one ultrawide monitor on top and the laptop's built-in display below it)

**Comment by gianmarcotoso** [comment] 2024-07-22 07:41
I have the same bug, but on a single ultrawide monitor. Using SUPER + ARROW KEYS to move windows around used to move windows between tiles in the layout, now it either moves it to the first or the last tile, or always to the centermost tile (I have a three column layout).

**Comment by bllooi** [comment] 2024-07-22 13:36
> Hey thank you for sharing this bug! Which monitor setup do you have? (For example, I tested in a setup having one ultrawide monitor on top and the laptop's built-in display below it)

Thanks for the prompt reply! Yeah I actually have 2 setups:

1. The same setup as you with my laptop at the bottom of an ultrawide. This issue is prevalent here. I am able to move the windows between the displays with "Super + Down / Up", however i cant use my left and right to move it between tiles in the active display
2. At work I have a monitor on the left and right, and my laptop sits in a dock. It's completely broken here. Moves the active window between the displays, doesn't move it between each tile.

**Comment by domferr** [comment] 2024-07-22 21:56
Hey guys, thanks a million for sharing so many important details. I managed to reproduce the problem and do a bugfix as well. I'm leaving here the files with the bugfix included. Let me know if it does fix the problem and if the keybindings are working good!

- GNOME shell version 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16340081/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME shell version 45 or 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16340083/tilingshell%40ferrarodomenico.com.zip)

**Comment by bllooi** [comment] 2024-07-23 06:35
Hey @domferr really appreciate the quick bug-to-fix time. Unfortunately this update did not work, the keybindings are still broken. The problem got a bit weirder on my side-by-side monitor.

1. If I move stuff to the right it will jump screens.
2. If I move stuff from the right screen to the left it will jump screens but to the correct position.

Did you do a force push? Didn't see any new commits, just a new commit time.

**Comment by domferr** [comment] 2024-07-23 06:49
Hey! Yeah, I did a force push to basically revert some previous changes.

The keybindings were not working on my side too and I spotted a regression in the source code. With a single monitor setup, it should be fixed, can you check that?

**Comment by domferr** [comment] 2024-07-23 06:58
Meanwhile, I'm reasoning about the problem related to multiple monitors.

May be related to the layout you are using? Let's say you use the keybindings to move a window to the right: the tiles the algorithm will take into account are the ones that start after the end of the window.
If the algorithm doesn't pick a tile on the current screen, it will select the nearest tile in the other screen.

P.S.: I do think this is not a good algorithm tbh, hope to improve it soon

**Comment by richardnpaul** [comment] 2024-07-23 07:56
I have two layouts (neither are any of the defaults which I removed).  One which is a 50/50 split (I've been meaning to raise an issue for an improvement on this front), the other is a 50% split of the screen width and then a further 50% split for one halves for the monitor height (so one full height half width split and then two roughly quarter splits in the other half).

I did manage to get moving a screen about working but not as it was working when I downloaded and started using the extension yesterday, but the update I picked up this morning is really barely functional.  I can't move a window down into the bottom quarter of my split.  My monitors (UHD) are arranged side by side, left side is just halves right side is the half and two quarters arrangement. I did find that if I maximise the window with Super + up arrow then I can use Super + left/right arrows but I can't use Super + Down arrow to move down from the top split to the bottom split.  Hopefully that helps

**Comment by bllooi** [comment] 2024-07-23 08:49
@domferr I attempted to use other combinations of layouts to no avail

My original layout was a 50/50 split similar to @richardnpaul. 

Btw are you running wayland or x11? How do you determine the positions of the screens are you using something like wmctrl or something? I know xdotool has a binding for typescript but it doesnt work on wayland

**Comment by domferr** [comment] 2024-07-24 08:23
Hey guys, thank you once again for sharing so many useful information. I have a guess of what could be the problem, however I'm not at home and I'll have access to my multi-monitor setup not earlier than tomorrow. I'm leaving here a bugfix, if you could try and let me know if it solves the problem it would be great! Thank you <3

- GNOME shell version 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16359292/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME shell version 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16359294/tilingshell%40ferrarodomenico.com.zip)

___

> I can't use Super + Down arrow to move down from the top split to the bottom split

@richardnpaul I don't know yet if it this is related to the other bug, let me know if that is fixed now!

> Btw are you running wayland or x11? How do you determine the positions of the screens are you using something like wmctrl or something? I know xdotool has a binding for typescript but it doesnt work on wayland

@bllooi I'm on wayland! I don't use any external tool, instead, Tiling Shell leverages on the GNOME API (GJS) and uses the provided Meta, Clutter and St to do everything, even determining positions on the screen and moving windows.

**Comment by gianmarcotoso** [comment] 2024-07-24 08:42
@domferr I can confirm that on a single monitor setup the keyboard shortcuts are working again with the linked version on Gnome 46. Thank you!

**Comment by richardnpaul** [comment] 2024-07-24 08:57
Okay, I can confirm that the version for Gnome 42 works on Ubuntu 22.04 with Gnome 42.9 for left and right movements full width splits within a monitor @domferr :+1:  Thanks for the work on getting this resolved.

I just noticed that my layouts had been changed.  Resetting now allows me to use the Super + Up/Down again to fit into a quarter so maybe the update to the extension reset my monitor layouts :thinking:

**Comment by bllooi** [comment] 2024-07-25 02:48
@domferr Looks like the keyboard issue is fixed! One issue I do see is that while window snapping, it does not respect the custom layouts set by the user. It defaults to the quarter layout for all snapping. Keyboard window movements are perfect now accross multiple displays.

Please see attached.
![2024-07-25_10-44](https://github.com/user-attachments/assets/8e923569-6a3d-43dc-bb35-2e172b93baf2)

**Comment by hrandib** [comment] 2024-07-25 06:24
Works fine again on my 3 monitors setup. Thanks!

**Comment by domferr** [comment] 2024-07-25 07:20
Thank you guys! I'll publish this update soon :soon: 

> One issue I do see is that while window snapping, it does not respect the custom layouts set by the user.

@bllooi sorry, I didn't understand what do you mean. Can you share a video or some steps to reproduce that? Thanks!

**Comment by richardnpaul** [comment] 2024-07-25 08:44
I see what he means, take the first tiling video in the README, this doesn't work this way with that layout now, it only works with halves and quarters.

**Comment by domferr** [comment] 2024-07-25 09:42
> I see what he means, take the [first tiling video](https://github.com/domferr/tilingshell?tab=readme-ov-file#tiling-system) in the README, this doesn't work this way with that layout now, it only works with halves and quarters.

Hmmm...

So, with that layout, you don't have the following behavior? Instead, what's happening when you drag and snap a window or when you move it using keybindings?

[Screencast from 2024-07-25 11-33-28.webm](https://github.com/user-attachments/assets/1483e206-a64c-4d67-8648-b9c60d14ed8f)
___
> I just noticed that my layouts had been changed. Resetting now allows me to use the Super + Up/Down again to fit into a quarter so maybe the update to the extension reset my monitor layouts 🤔

@richardnpaul That shouldn't happen because the extension saves the layouts using `dconf`, so updates of Tiling Shell use your saved layouts, there is definitely something strange that is going on here... I'll investigate! Thank you

**Comment by richardnpaul** [comment] 2024-07-25 11:31
Here's what I see with the zip package from yesterday:
[Screencast from 25-07-24 12:27:55.webm](https://github.com/user-attachments/assets/4271cfbd-d0b9-4b21-a70a-4c9a0b0ac8a3)

**Comment by domferr** [comment] 2024-07-25 15:22
Uh! I see where the confusion is coming from ahahah

The active layout is used by the key bindings and the tiling system, but not yet when dragging a window to the edge. The latter can be enabled pressing an action key (`CTRL` by default, but it can be changed from Tiling Shell's preferences). If you look at my video, I keep pressing `CTRL` key while moving a window to show the tiling system.

Dragging a window to the edge doesn't use the active layout. It will always use a quarter tiling layout, since it was implemented recently just to extend GNOME's default behaviour. I'm going to upgrade it soon.

**Comment by richardnpaul** [comment] 2024-07-25 18:32
Okay so if everyone else agrees I think that you can release the change with the fix for the keyboard shortcuts and we can get back onto the released versions for those of us using the zipped versions that you linked to in here and then this can get closed off.

Thanks for all your feedback and work on this 👏

**Comment by bllooi** [comment] 2024-07-26 02:38
@richardnpaul thanks alot for expanding on my observation and providing a video! Hahaha was going to do it myself.

@domferr yeah i can confirm that using the modifier key does work. thank you so much for all the work and feedback.

**Comment by domferr** [comment] 2024-07-29 16:22
:heavy_check_mark: Done in version 12.1! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Closed by domferr** 2024-07-29 16:22 UTC
Labels: bug, next release
