### ISSUE TITLE
[Feature Request] Keyboard Shortcuts

### ISSUE THREAD

**Issue by ebits21** [domferr/tilingshell#36] opened 2024-06-19 00:37 UTC
In Windows it's nice to move windows into half/quarter tiles using the Windows key and the arrows on the keyboard.

I would like some way of fitting a window into the tiling layout using only the keyboard. This is much nicer when on a laptop compared to using the mouse to place windows into the tiling layout.

As layouts are varied, I suggest, as possibilities:

1) A keyboard shortcut to cycle the current window through different open positions in the current Layout. Alternatively, could just cycle the window to the next position in the layout and overlay a window if it is already there.
2) A keyboard shortcut to change the current layout to the next layout.
3) If default quarter tiling is implemented, allow the Super key plus arrows to quarter tile the current tile, like on Windows.
4) A keyboard shortcut to change the focused window. Maybe this already exists in Gnome?

**Comment by joaocandre** [comment] 2024-06-19 02:10
Came here to create a post on this, glad to know I'm not the only one thinking this. Very well designed extension overall, but indeed missing keybindings to streamline window tiling.

**Comment by ebits21** [comment] 2024-06-19 10:44
Awesome, will check it out if I get a chance 😎

**Comment by joaocandre** [comment] 2024-06-20 02:17
>  it will be possible to use Super key + arrows to cycle the current window through the tiles of the current Layout (your first idea!).

Will it be possible to assign shortcuts/combinations to specific tiles?

**Comment by domferr** [comment] 2024-06-20 08:26
> > it will be possible to use Super key + arrows to cycle the current window through the tiles of the current Layout (your first idea!).
> 
> Will it be possible to assign shortcuts/combinations to specific tiles?

That is not planned since I'm aiming to extend GNOME's default behaviour

**Comment by joaocandre** [comment] 2024-06-20 12:13
Fair enough, but how would one deal with multiple layouts? Is only the first layout considered in that case?

**Comment by domferr** [comment] 2024-06-21 08:38
> Fair enough, but how would one deal with multiple layouts? Is only the first layout considered in that case?

No, when pressing `Super key + arrows`, the currently selected layout will be taken into consideration

**Comment by kaanaksit** [comment] 2024-06-21 20:47
> Hey thank you for this suggestion! This is actually under development: in version v9.0 it will be possible to use Super key + arrows to cycle the current window through the tiles of the current Layout (your first idea!).
> 
> If you wanna try it in advance, I'll leave attached the new version currently under development.
> 
>     * GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15897186/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
> 
>     * GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15897188/tilingshell%40ferrarodomenico.com.zip)
> 
> 
> > A keyboard shortcut to change the current layout to the next layout.
> 
> That was not being considered, I'll think about it!

This works perfectly. I can not describe how functional this keybinding is. Gnome has needed this for so long. I look forward to seeing this new version moving to a stable version soon.

**Comment by domferr** [comment] 2024-06-21 20:50
> > Hey thank you for this suggestion! This is actually under development: in version v9.0 it will be possible to use Super key + arrows to cycle the current window through the tiles of the current Layout (your first idea!).
> > If you wanna try it in advance, I'll leave attached the new version currently under development.
> > ```
> > * GNOME 42, 43 and 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15897186/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
> > 
> > * GNOME 45 and 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/15897188/tilingshell%40ferrarodomenico.com.zip)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > A keyboard shortcut to change the current layout to the next layout.
> > 
> > 
> > That was not being considered, I'll think about it!
> 
> This works perfectly. I can not describe how functional this keybinding is. Gnome has needed this for so long. I look forward to seeing this new version moving to a stable version soon.

Hey @kaanaksit I'm happy you are enjoying it! The good news is that the new version (the one you tried) is already under review and will be published soon! Feel free to open a new issue for any bug or for sharing any cool idea!

**Comment by domferr** [comment] 2024-06-22 14:20
:heavy_check_mark: Completed in version 9.0! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>

**Closed by domferr** 2024-06-22 14:20 UTC
Labels: enhancement

**Comment by joaocandre** [comment] 2024-06-23 17:44
Cool addition, it becomes much more practical to tile windows this way.

A couple of observations though, which I'm not sure if bugs or intended behavior: 
- When a window is tiled the default 'untile' shortcut (Super + Down) no longer works;
- If you 'maximize' and then 'unmaximize' a tiled window (Super + Up followed by Super + Down) the extension bindings no longer seem to work (you need to drag the window to re-enable them)

Lastly, it would be cool to have an additional binding to cycle through available layouts, not sure if that's planned for future releases.

**Comment by kaanaksit** [comment] 2024-06-23 17:49
Honestly, I like the new behavior more than the default with super + down or up as it provides an easy way to move around a window around the screen. Please consider keep it as is.
